### ISSUE TITLE
Blazor css messes with tabs

### ISSUE THREAD

**Issue by timbze** [chanan/BlazorStrap#322]
Blazor has a default style in site.css which makes tabs look like this by default.
![image](https://user-images.githubusercontent.com/35117769/81345392-9e527980-9075-11ea-9eb7-d426922bb3d5.png)

The snippet in site.css that gives the problem is this:
```css

.nav-item:first-of-type {
    padding-top: 1rem;
}

.nav-item:last-of-type {
    padding-bottom: 1rem;
}
```
