### ISSUE TITLE
Breadcrumb link class

### ISSUE THREAD

**Issue by marcOcram** [chanan/BlazorStrap#553]
Hello,

I switched to BlazorStrap past week and have an issue with the links inside the Breadcrumb. I would like to add the class "link-secondary" to alter the color of the link. This is currently not possible: https://github.com/chanan/BlazorStrap/blob/1fd9f4d4bd8bcb8eb7051fbbb851bb7920c7645e/src/BlazorStrap.V5/Components/Common/BSBreadcrumb.razor#L27

The workaround is to use a CSS with the values copied from bootstrap.css

```css
::deep li.breadcrumb-item > a {
    /* values copied from bootstrap class link-secondary */
    color: #6c757d !important;
}

::deep li.breadcrumb-item > a:hover, ::deep li.breadcrumb-item > a:focus {
    /* values copied from bootstrap class link-secondary:hover, link-secondary:focus */
    color: #565e64 !important;
}
```

Is it planned to get support to alter the link's class?
